// <auto-generated />
using System;
using CourSoutienApp2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CourSoutienApp2.Migrations.CoursDb
{
    [DbContext(typeof(CoursDbContext))]
    partial class CoursDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CourSoutienApp2.Models.Cours", b =>
                {
                    b.Property<int>("CoursId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Heured")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Heuref")
                        .HasColumnType("datetime2");

                    b.Property<string>("Intitule")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Lieu")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prof")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CoursId");

                    b.ToTable("Cours");
                });
#pragma warning restore 612, 618
        }
    }
}
